"""Write docs/COMMANDS.md from the live tool registry.

    python scripts/generate_command_list.py          # rewrite the file
    python scripts/generate_command_list.py --check  # exit 1 if it is stale

One row per tool: what it does (the first sentence of its description), its four
annotation hints, and whether the safeguard can hold it for the owner's approval.
tests/test_command_list_in_sync.py fails when the file and the registry disagree.
"""

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
OUTPUT = ROOT / "docs" / "COMMANDS.md"

_SAFEGUARD = {
    "free": "runs",
    "gated": "**asks the owner**",
    "seen_signal": "asks while ghost mode is on",
    "send": "runs; asks for a first message, a bulk send or untrusted content",
}


def _first_sentence(text: str) -> str:
    flat = " ".join((text or "").split())
    match = re.match(r"(.+?[.!?])(\s|$)", flat)
    sentence = match.group(1) if match else flat
    return sentence.replace("|", "\\|")


def _hints(annotations) -> str:
    flags = [
        ("R", annotations.read_only_hint),
        ("D", annotations.destructive_hint),
        ("I", annotations.idempotent_hint),
        ("O", annotations.open_world_hint),
    ]
    return " ".join(letter if value else "-" for letter, value in flags)


def render() -> str:
    from telegram_mcp.safeguard import policy
    from telegram_mcp.tools import mcp

    groups = defaultdict(list)
    for tool in mcp._tool_manager.list_tools():
        module = getattr(tool.fn, "__module__", "") or ""
        groups[module.rsplit(".", 1)[-1]].append(tool)

    total = sum(len(tools) for tools in groups.values())
    lines = [
        "# Command list",
        "",
        "<!-- Generated by scripts/generate_command_list.py - do not edit by hand. -->",
        "",
        f"Every tool this server exposes: **{total}**, grouped by the module that defines it.",
        "",
        "**Hints** are the four MCP annotations: **R**ead-only, **D**estructive "
        "(not purely additive, in MCP's sense), **I**dempotent, **O**pen-world; `-` means "
        "false. **Safeguard** says what happens when an agent calls the tool: see "
        "[INSTALL.md](INSTALL.md#the-safeguard). Any write call is also held when its "
        "arguments carry text another person wrote, a file tool is held when its path "
        "leaves `files/outbox` and `files/downloads`, and a call is refused outright when "
        "it would touch the approval channel, the safeguard's own files, the rest of the "
        "installation or the state directory.",
        "",
    ]
    for module in sorted(groups):
        lines += [
            f"## {module}",
            "",
            "| Tool | What it does | Hints | Safeguard |",
            "|---|---|---|---|",
        ]
        for tool in sorted(groups[module], key=lambda t: t.name):
            a = tool.annotations
            category = policy.categorize(
                tool.name, bool(a.read_only_hint), bool(a.destructive_hint)
            )
            if tool.name == "set_ghost_mode":
                safeguard = "turning on runs; turning off **asks the owner**"
            else:
                safeguard = _SAFEGUARD[category]
            lines.append(
                f"| `{tool.name}` | {_first_sentence(tool.description)} | "
                f"`{_hints(a)}` | {safeguard} |"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print("docs/COMMANDS.md is stale; run scripts/generate_command_list.py")
            return 1
        print("docs/COMMANDS.md is current")
        return 0
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
